name: 📚 Docs
on:
  workflow_dispatch:
  workflow_call:
  push:
    tags:
      - "*"
permissions:
  id-token: write
  pages: write
defaults:
  run:
    shell: bash
    working-directory: ./docs
jobs:
  setup:
    name: 🔧 Request
    uses: ./.github/workflows/setup.yaml
  build:
    name: "📚 Build Docs"
    needs: setup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: 📦 Hydrate node_modules
        uses: actions/cache@v3
        id: hydrate-node-modules
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: 📊 Generate diagrams
        run: make diagrams
      - name: 📚 Build documentation
        run: npm run docs:build
      - name: 📤 Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: tmp/build
      - id: deployment
        name: 📤 Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
      - name: cicd app auth
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CICD_APP_ID }}
          private-key: ${{ secrets.CICD_APP_PRIVATE_KEY }}
      - name: 🔧 Commit and push diagrams
        run: |
          git config --global user.name "svelte-dynamic-component-engine[bot]"
          git config --global user.email "svelte-dynamic-component-engine[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}.git
          git add .
          git commit -am "chore(docs): update diagrams"
          git push origin HEAD:main
